export const elementos = {
    URL: "https://www.cobasi.com.br/",
    campoPesquisa: '[class="jss5"]',
    nomeProduto: "Biofresh",
    validadorProduto: "Ração Biofresh Gatos Castrados Salmão",
    linkProduto: '[href="/racao-biofresh-gatos-castrados-salmao-31004174/p"]',
    botaoQuantidade: '[class="MuiChip-label"]',
    botaoAdicionarItem: '[class="styles__ButtonWrapper-sc-1nkubcs-0 dUwffV button-new"]',
    validadorCarrinho: "Produto adicionado ao Carrinho",
    botaoCarrinho: '[class="styles__LinkWrapper-sc-1nkubcs-3 eoHhru"]',
    botaoAumentarQuantidade: '[class="svg-inline--fa fa-plus fa-1x "]', 
    validadorQuantidadeMaior: "2",
    botaoDiminuirQuantidade: '[class="svg-inline--fa fa-minus fa-1x "]',
    validadorQuantidadeMenor: "1",
    botaoFinalizarCompra:'[class="styles__Wrapper-sc-nahdkg-0 iesoOZ"]',
    validadorLogin: "Acesse sua conta",
    camposLogin: '[class="MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd"]',
    valorUsuario: "teste@teste.com.br",
    valorSenha: 123456,
    validadorLogin: "E-mail ou senha inválidos.",
}
